import { useMemo, useState } from 'react'
import { Check, ChevronDown, FileCheck2, Heart, MapPin, PackageCheck, Plus, Search, SlidersHorizontal, Star, Truck, X } from 'lucide-react'
import type { Lang, View } from './voiceTypes'
import type { BuyerRequirement, Transaction, TransactionStatus } from './dataTypes'
import './marketplace.css'

type Product = { id: string; title: string; producer: string; location: string; litres: string; price: string; rating: string; category: string; image: string; badge?: string; description: string; mg: number }
const products: Product[] = [
  { id: 'BT-1042', title: 'Refined magnesium-rich bittern', producer: 'Arul Salt Works', location: 'Thoothukudi', litres: '10,000 L available', price: '₹11.80 / L', rating: '4.9', category: 'Magnesium', badge: 'Best match', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=85', description: 'Consistent magnesium concentration, producer-documented and ready for industrial recovery.', mg: 8.4 },
  { id: 'AG-2207', title: 'Aggregated coastal bittern supply', producer: '3 verified producers', location: 'Thoothukudi region', litres: '23,000 L available', price: '₹10.90 / L', rating: '4.8', category: 'Aggregated', badge: 'High volume', image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=85', description: 'A consolidated consignment designed for processors that need reliable industrial volume.', mg: 8.2 },
  { id: 'BT-1038', title: 'Clean bromine recovery feedstock', producer: 'Meenakshi Pan', location: 'Thoothukudi', litres: '5,000 L available', price: '₹9.70 / L', rating: '4.7', category: 'Bromine', image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=85', description: 'Traceable salt-pan by-product with a clear availability window and collection details.', mg: 8.1 },
  { id: 'BT-1031', title: 'Potassium-ready bittern batch', producer: 'Seabird Salts', location: 'Ramanathapuram', litres: '8,000 L available', price: '₹8.90 / L', rating: '4.6', category: 'Potassium', image: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=85', description: 'A flexible batch for potassium recovery and blended industrial applications.', mg: 8.7 },
]
const statusOrder: TransactionStatus[] = ['Offer sent', 'Negotiating', 'Accepted', 'Sample requested', 'Pickup scheduled', 'In transit', 'Delivered']

export function BuyerMarketplace({ lang, transactions, setTransactions, requirements, setRequirements, onNavigate }: { lang: Lang; transactions: Transaction[]; setTransactions: (items: Transaction[]) => void; requirements: BuyerRequirement[]; setRequirements: (items: BuyerRequirement[]) => void; onNavigate?: (view: View) => void }) {
  const isTamil = lang === 'ta'
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All products')
  const [sort, setSort] = useState('Recommended')
  const [favorites, setFavorites] = useState<string[]>([])
  const [selected, setSelected] = useState<Product | null>(null)
  const [showFilters, setShowFilters] = useState(false)
  const [showRequirement, setShowRequirement] = useState(false)
  const [showTransactions, setShowTransactions] = useState(false)
  const [minVolume, setMinVolume] = useState(0)
  const [maxDistance, setMaxDistance] = useState('Any distance')
  const [offerPrice, setOfferPrice] = useState('11.80')
  const categories = isTamil ? ['அனைத்தும்', 'மெக்னீசியம்', 'புரோமின்', 'பொட்டாசியம்', 'திரட்டப்பட்டவை'] : ['All products', 'Magnesium', 'Bromine', 'Potassium', 'Aggregated']
  const categoryMap: Record<string, string> = isTamil ? { 'அனைத்தும்': 'All products', 'மெக்னீசியம்': 'Magnesium', 'புரோமின்': 'Bromine', 'பொட்டாசியம்': 'Potassium', 'திரட்டப்பட்டவை': 'Aggregated' } : {}
  const filtered = useMemo(() => {
    const result = products.filter((product) => ((categoryMap[category] ?? category) === 'All products' || product.category === (categoryMap[category] ?? category)) && product.title.toLowerCase().includes(query.toLowerCase()) && Number(product.litres.replace(/[^0-9]/g, '')) >= minVolume)
    if (sort === 'Price: low to high') return [...result].sort((a, b) => Number(a.price.replace(/[^0-9.]/g, '')) - Number(b.price.replace(/[^0-9.]/g, '')))
    if (sort === 'Volume: high to low') return [...result].sort((a, b) => Number(b.litres.replace(/[^0-9]/g, '')) - Number(a.litres.replace(/[^0-9]/g, '')))
    return result
  }, [category, categoryMap, minVolume, query, sort])
  const toggleFavorite = (id: string) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const sendOffer = (product: Product) => {
    const next: Transaction = { id: `TX-${Date.now().toString().slice(-5)}`, batchId: product.id, buyer: 'MagCore Industries', producer: product.producer, litres: Number(product.litres.replace(/[^0-9]/g, '')), price: Number(offerPrice) || 11.8, status: 'Offer sent', updatedAt: 'Just now', note: 'Awaiting producer response.' }
    setTransactions([next, ...transactions.filter((item) => item.batchId !== product.id)])
    setSelected(null)
    onNavigate?.('transactions')
  }
  const advance = (transaction: Transaction) => { const next = statusOrder[Math.min(statusOrder.indexOf(transaction.status) + 1, statusOrder.length - 1)]; setTransactions(transactions.map((item) => item.id === transaction.id ? { ...item, status: next, updatedAt: 'Just now' } : item)) }
  const addRequirement = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setRequirements([{ id: `REQ-${Date.now().toString().slice(-4)}`, buyer: 'MagCore Industries', material: String(form.get('material')), litres: Number(form.get('litres')) || 15000, minMg: Number(form.get('minMg')) || 7.5, district: String(form.get('district')), deadline: String(form.get('deadline')), status: 'Active' }, ...requirements]); setShowRequirement(false) }

  return <div className="marketplace-page">
    <section className="marketplace-hero"><div><span className="marketplace-kicker">{isTamil ? 'அளம் சந்தை' : 'ALAM MARKETPLACE'}</span><h1>{isTamil ? 'உங்களுக்கான பிடர்னை கண்டறியுங்கள்.' : 'Find the right bittern for your process.'}</h1><p>{isTamil ? 'சரிபார்க்கப்பட்ட உற்பத்தியாளர்களிடமிருந்து நேரடியாக உலாவி, ஒப்பிட்டு, தொடர்பு கொள்ளுங்கள்.' : 'Browse verified supply, compare fit, and move from an offer to a traceable delivery.'}</p></div><div className="marketplace-hero-stat"><strong>4.8<span>/5</span></strong><small>{isTamil ? 'உற்பத்தியாளர் மதிப்பீடு' : 'producer rating'}</small></div></section>
    <div className="marketplace-search-row"><div className="marketplace-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={isTamil ? 'பிடர்ன், உற்பத்தியாளர் அல்லது இடத்தை தேடுங்கள்' : 'Search bittern, producer, or location'} /></div><button className="marketplace-filter" onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={17} />{isTamil ? 'வடிகட்டு' : 'Filters'}</button><button className="marketplace-bag" onClick={() => onNavigate?.('transactions')}><PackageCheck size={17} />{transactions.length}<span>{isTamil ? 'பரிவர்த்தனைகள்' : 'Transactions'}</span></button></div>
    {showFilters && <div className="marketplace-filter-panel"><label>Minimum volume <select value={minVolume} onChange={(event) => setMinVolume(Number(event.target.value))}><option value="0">Any volume</option><option value="5000">5,000 L+</option><option value="10000">10,000 L+</option><option value="20000">20,000 L+</option></select></label><label>Maximum distance <select value={maxDistance} onChange={(event) => setMaxDistance(event.target.value)}><option>Any distance</option><option>50 km</option><option>100 km</option><option>250 km</option></select></label><span>{maxDistance === 'Any distance' ? 'Showing all collection routes' : `Showing routes within ${maxDistance}`}</span></div>}
    <div className="marketplace-controls"><div className="marketplace-categories">{categories.map((item) => <button key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><label className="marketplace-sort">{isTamil ? 'வரிசைப்படுத்து' : 'Sort by'}<select value={sort} onChange={(event) => setSort(event.target.value)}><option>Recommended</option><option>Price: low to high</option><option>Volume: high to low</option></select><ChevronDown size={14} /></label></div>
    <div className="marketplace-meta"><b>{filtered.length} {isTamil ? 'விநியோகங்கள்' : 'supplies'}</b><span>{isTamil ? 'பொருத்தமான உற்பத்தியாளர்களிடமிருந்து' : 'from matched producers'}</span><button className="text-button requirement-button" onClick={() => onNavigate?.('requirements')}><Plus size={14} />{isTamil ? 'தேவை உருவாக்கு' : 'Create requirement'}</button></div>
    <div className="product-grid">{filtered.map((product) => <article className="product-card" key={product.id}><div className="product-image"><img src={product.image} alt={product.title} /><span className="product-badge">{product.badge ?? product.category}</span><button className={favorites.includes(product.id) ? 'favorite active' : 'favorite'} onClick={() => toggleFavorite(product.id)} aria-label={isTamil ? 'சேமி' : 'Save product'}><Heart size={17} fill={favorites.includes(product.id) ? 'currentColor' : 'none'} /></button></div><div className="product-body"><div className="product-rating"><Star size={13} fill="currentColor" /> {product.rating}<span>· {product.id}</span></div><h2>{product.title}</h2><p className="product-producer">{product.producer}</p><p className="product-description">{product.description}</p><div className="product-location"><MapPin size={13} />{product.location}<span>·</span><Truck size={13} />{product.litres}</div><div className="product-footer"><strong>{product.price}</strong><button onClick={() => setSelected(product)}>{isTamil ? 'விவரங்கள்' : 'View details'}</button></div></div></article>)}</div>
    {showTransactions && <TransactionPanel lang={lang} transactions={transactions} onAdvance={advance} onClose={() => setShowTransactions(false)} />}
    {showRequirement && <div className="marketplace-modal-backdrop"><form className="product-detail-modal requirement-modal" onSubmit={addRequirement}><div className="product-detail-copy"><button type="button" className="modal-close" onClick={() => setShowRequirement(false)}><X size={18} /></button><span className="marketplace-kicker">BUYER DEMAND</span><h2>Create a supply requirement</h2><p>Publish the exact material and volume your process needs. Matching producers can respond with a traceable offer.</p><div className="requirement-form"><label>Material<input name="material" defaultValue="Magnesium recovery" /></label><label>Required volume (L)<input name="litres" type="number" defaultValue="15000" /></label><label>Minimum Mg (%)<input name="minMg" type="number" step="0.1" defaultValue="7.5" /></label><label>District<input name="district" defaultValue="Thoothukudi" /></label><label>Deadline<input name="deadline" type="date" defaultValue="2026-09-30" /></label></div><button className="primary-button full" type="submit"><Plus size={15} />Publish requirement</button></div></form></div>}
    {selected && <div className="marketplace-modal-backdrop" onClick={() => setSelected(null)}><div className="product-detail-modal" onClick={(event) => event.stopPropagation()}><img src={selected.image} alt={selected.title} /><div className="product-detail-copy"><button className="modal-close" onClick={() => setSelected(null)}><X size={18} /></button><span className="marketplace-kicker">{selected.id} · {selected.category}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="detail-lines"><span><MapPin size={15} />{selected.location}</span><span><Truck size={15} />{selected.litres}</span><span><FileCheck2 size={15} />Producer documented · {selected.mg}% Mg</span></div><strong className="detail-price">₹{offerPrice} / L</strong><label className="offer-price">Your offer price / L<input value={offerPrice} onChange={(event) => setOfferPrice(event.target.value)} /></label><button className="primary-button marketplace-offer" onClick={() => sendOffer(selected)}><Check size={15} />Request offer</button><div className="traceability-chip"><span className="fake-qr">▦</span><span><b>Traceability record ready</b><small>QR record generated when accepted</small></span></div></div></div></div>}
  </div>
}

function TransactionPanel({ lang, transactions, onAdvance, onClose }: { lang: Lang; transactions: Transaction[]; onAdvance: (transaction: Transaction) => void; onClose: () => void }) { const isTamil = lang === 'ta'; return <div className="transaction-panel"><div className="transaction-heading"><div><span className="marketplace-kicker">{isTamil ? 'பரிவர்த்தனைகள்' : 'TRANSACTION DESK'}</span><h2>{isTamil ? 'சலுகையிலிருந்து விநியோகம் வரை' : 'Offers to delivery'}</h2></div><button onClick={onClose}><X size={18} /></button></div>{transactions.map((transaction) => { const index = statusOrder.indexOf(transaction.status); return <article className="transaction-card" key={transaction.id}><div className="transaction-card-top"><div><b>{transaction.batchId}</b><span>{transaction.producer} · {transaction.litres.toLocaleString()} L</span></div><strong>{transaction.status}</strong></div><div className="transaction-progress">{statusOrder.map((status, i) => <i className={i <= index ? 'done' : ''} key={status} title={status} />)}</div><div className="transaction-card-bottom"><span>{transaction.updatedAt} · ₹{transaction.price.toFixed(2)} / L</span>{index < statusOrder.length - 1 && <button className="outline-button" onClick={() => onAdvance(transaction)}>{index === 0 ? 'Counter / accept' : index === 2 ? 'Request sample' : index === 3 ? 'Schedule pickup' : 'Advance status'}<ChevronDown size={14} /></button>}<span className="qr-record"><span className="fake-qr small">▦</span> QR trace</span></div></article>})}</div> }
