import * as React from 'react'
import { BarChart3, Bell, CalendarClock, Check, FileCheck2, PackageCheck, QrCode, Route, ShieldCheck, Truck, Upload, Users, X } from 'lucide-react'
import type { BuyerRequirement, Notification, Transaction, TransactionStatus } from './dataTypes'
import type { Lang } from './voiceTypes'
import './feature-pages.css'

const statuses: TransactionStatus[] = ['Offer sent', 'Negotiating', 'Accepted', 'Sample requested', 'Pickup scheduled', 'In transit', 'Delivered']

type PageProps = { lang: Lang }

export function TransactionsPage({ lang, transactions, setTransactions }: PageProps & { transactions: Transaction[]; setTransactions: (items: Transaction[]) => void }) {
  const isTamil = lang === 'ta'
  const advance = (transaction: Transaction) => { const index = statuses.indexOf(transaction.status); const next = statuses[Math.min(index + 1, statuses.length - 1)]; setTransactions(transactions.map((item) => item.id === transaction.id ? { ...item, status: next, updatedAt: 'Just now' } : item)) }
  return <FeatureShell eyebrow="TRANSACTION DESK" title={isTamil ? 'சலுகைகள் மற்றும் விநியோகம்' : 'Offers and deliveries'} sub={isTamil ? 'ஒவ்வொரு ஒப்பந்தத்தையும் அதன் அடுத்த செயல்பாட்டுடன் நிர்வகிக்கவும்.' : 'Manage every offer through acceptance, sampling, pickup, and delivery.'} icon={PackageCheck}><div className="feature-stat-row"><FeatureStat label="Active transactions" value={String(transactions.length)} /><FeatureStat label="Volume in workflow" value={`${transactions.reduce((sum, item) => sum + item.litres, 0).toLocaleString()} L`} /><FeatureStat label="Delivered" value={String(transactions.filter((item) => item.status === 'Delivered').length)} /></div><div className="feature-list">{transactions.map((transaction) => { const index = statuses.indexOf(transaction.status); return <article className="workflow-card" key={transaction.id}><div className="workflow-card-head"><div><span className="feature-id">{transaction.id}</span><h3>{transaction.batchId} · {transaction.producer}</h3><p>{transaction.buyer} · {transaction.litres.toLocaleString()} L · ₹{transaction.price.toFixed(2)} / L</p></div><strong className="status-pill">{transaction.status}</strong></div><div className="status-track">{statuses.map((status, step) => <span className={step <= index ? 'complete' : ''} key={status}><i />{status}</span>)}</div><div className="workflow-footer"><span>{transaction.updatedAt}{transaction.note ? ` · ${transaction.note}` : ''}</span>{index < statuses.length - 1 && <button className="primary-button" onClick={() => advance(transaction)}>{index === 0 ? 'Move to negotiation' : index === 2 ? 'Request sample' : index === 3 ? 'Schedule pickup' : 'Advance workflow'}<Check size={15} /></button>}</div></article>})}</div></FeatureShell>
}

export function RequirementsPage({ lang, requirements, setRequirements }: PageProps & { requirements: BuyerRequirement[]; setRequirements: (items: BuyerRequirement[]) => void }) {
  const [open, setOpen] = React.useState(false)
  const add = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setRequirements([{ id: `REQ-${Date.now().toString().slice(-4)}`, buyer: 'MagCore Industries', material: String(form.get('material')), litres: Number(form.get('litres')) || 15000, minMg: Number(form.get('minMg')) || 7.5, district: String(form.get('district')), deadline: String(form.get('deadline')), status: 'Active' }, ...requirements]); setOpen(false) }
  return <FeatureShell eyebrow="BUYER DEMAND" title={lang === 'ta' ? 'விநியோக தேவைகள்' : 'Supply requirements'} sub="Publish and manage the exact industrial demand you need fulfilled." icon={Users} action={<button className="primary-button" onClick={() => setOpen(true)}>Create requirement</button>}><div className="feature-list requirement-list">{requirements.map((requirement) => <article className="requirement-card" key={requirement.id}><div className="requirement-icon"><Users size={19} /></div><div><span className="feature-id">{requirement.id} · {requirement.status}</span><h3>{requirement.material}</h3><p>{requirement.buyer} needs {requirement.litres.toLocaleString()} L with at least {requirement.minMg}% Mg in {requirement.district}.</p></div><div className="requirement-meta"><b>{requirement.deadline}</b><small>Deadline</small></div></article>)}</div>{open && <div className="feature-modal"><form className="feature-form" onSubmit={add}><button type="button" className="feature-close" onClick={() => setOpen(false)}><X size={18} /></button><span className="feature-id">NEW DEMAND SIGNAL</span><h2>Create requirement</h2><label>Material<input name="material" defaultValue="Magnesium recovery" /></label><label>Required volume (L)<input name="litres" type="number" defaultValue="15000" /></label><label>Minimum Mg (%)<input name="minMg" type="number" step="0.1" defaultValue="7.5" /></label><label>District<input name="district" defaultValue="Thoothukudi" /></label><label>Deadline<input name="deadline" type="date" defaultValue="2026-09-30" /></label><button className="primary-button full" type="submit">Publish requirement <Check size={15} /></button></form></div>}</FeatureShell>
}

export function LogisticsPage({ lang, transactions }: PageProps & { transactions: Transaction[] }) { return <FeatureShell eyebrow="FULFILMENT CONTROL" title={lang === 'ta' ? 'தளவாட திட்டமிடல்' : 'Logistics control'} sub="Coordinate collection windows, transport, and delivery milestones." icon={Truck}><div className="logistics-grid"><FeaturePanel icon={CalendarClock} title="Next pickup window"><strong>18 Sep 2026 · 09:00–12:00</strong><p>BT-1042 · Thoothukudi collection point</p><button className="outline-button">Assign transport partner</button></FeaturePanel><FeaturePanel icon={Route} title="Route plan"><strong>42 km collection radius</strong><p>One coordinated truck can serve three compatible producers.</p><button className="outline-button">Compare transport cost</button></FeaturePanel></div><div className="feature-list">{transactions.map((item) => <article className="logistics-row" key={item.id}><Truck size={18} /><div><b>{item.batchId} · {item.producer}</b><span>{item.status} · {item.litres.toLocaleString()} L</span></div><strong>{item.status === 'Delivered' ? 'Complete' : 'Needs scheduling'}</strong></article>)}</div></FeatureShell> }

export function TraceabilityPage({ lang, transactions }: PageProps & { transactions: Transaction[] }) { return <FeatureShell eyebrow="TRUSTED MOVEMENT" title={lang === 'ta' ? 'கண்காணிப்பு பதிவுகள்' : 'Traceability records'} sub="Every batch movement, document, and handoff in one auditable view." icon={QrCode}><div className="trace-grid">{transactions.map((item) => <article className="trace-card" key={item.id}><div className="qr-box"><QrCode size={48} /></div><div><span className="feature-id">{item.id}</span><h3>{item.batchId} · {item.producer}</h3><p>{item.litres.toLocaleString()} L moved toward {item.buyer}</p><div className="trace-tags"><span><FileCheck2 size={13} />Producer record</span><span><ShieldCheck size={13} />Verified handoff</span></div></div><button className="outline-button"><Upload size={14} />Export record</button></article>)}</div></FeatureShell> }

export function AnalyticsPage({ lang, batches }: PageProps & { batches: { litres: number; status: string }[] }) { const active = batches.filter((item) => item.status === 'Listed' || item.status === 'Matched'); return <FeatureShell eyebrow="PRODUCER PERFORMANCE" title={lang === 'ta' ? 'விநியோக பகுப்பாய்வு' : 'Supply analytics'} sub="Understand value, utilisation, and matching performance over time." icon={BarChart3}><div className="feature-stat-row"><FeatureStat label="Active supply" value={`${active.reduce((sum, item) => sum + item.litres, 0).toLocaleString()} L`} /><FeatureStat label="Average match" value="94%" /><FeatureStat label="Value growth" value="+18.4%" /></div><div className="analytics-chart"><div className="chart-bars"><i style={{ height: '45%' }} /><i style={{ height: '61%' }} /><i style={{ height: '54%' }} /><i style={{ height: '78%' }} /><i style={{ height: '68%' }} /><i style={{ height: '92%' }} /></div><div className="chart-labels"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></FeatureShell> }

export function VerificationPage({ lang }: PageProps) { return <FeatureShell eyebrow="TRUST CENTRE" title={lang === 'ta' ? 'சரிபார்ப்பு மையம்' : 'Verification centre'} sub="Build buyer confidence with transparent producer and batch documentation." icon={ShieldCheck}><div className="verification-steps">{[['Identity verified', 'Account and producer identity confirmed', Check], ['Documents verified', 'Business and storage records accepted', FileCheck2], ['Laboratory verified', 'Upload a current composition certificate', Upload]].map(([title, detail, Icon], index) => <article className={index < 2 ? 'verification-step complete' : 'verification-step'} key={title as string}><span><Icon size={18} /></span><div><h3>{title as string}</h3><p>{detail as string}</p></div><strong>{index < 2 ? 'Complete' : 'Next step'}</strong></article>)}</div></FeatureShell> }

export function NotificationsPage({ lang, notifications, setNotifications }: PageProps & { notifications: Notification[]; setNotifications: (items: Notification[]) => void }) { return <FeatureShell eyebrow="ACTIVITY CENTRE" title={lang === 'ta' ? 'அறிவிப்பு மையம்' : 'Notification centre'} sub="Keep every offer, demand signal, and workflow change visible." icon={Bell} action={<button className="outline-button" onClick={() => setNotifications(notifications.map((item) => ({ ...item, read: true })))}>Mark all as read</button>}><div className="feature-list notification-page-list">{notifications.map((item) => <button className={item.read ? 'page-notification read' : 'page-notification'} key={item.id} onClick={() => setNotifications(notifications.map((entry) => entry.id === item.id ? { ...entry, read: true } : entry))}><span className={`notification-tone ${item.tone}`} /><span><b>{item.title}</b><small>{item.detail}</small><em>{item.time}</em></span>{!item.read && <i />}</button>)}</div></FeatureShell> }

function FeatureShell({ eyebrow, title, sub, icon: Icon, action, children }: { eyebrow: string; title: string; sub: string; icon: any; action?: React.ReactNode; children: React.ReactNode }) { return <div className="feature-page"><header className="feature-header"><div className="feature-title"><span className="feature-icon"><Icon size={21} /></span><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{sub}</p></div></div>{action}</header>{children}</div> }
function FeatureStat({ label, value }: { label: string; value: string }) { return <div className="feature-stat"><span>{label}</span><strong>{value}</strong></div> }
function FeaturePanel({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) { return <section className="feature-panel"><Icon size={19} /><span className="eyebrow">{title}</span>{children}</section> }
