import { StrictMode, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import {
  ArrowUpRight, Bell, Check, ChevronRight, CircleHelp, Factory, FileCheck2, Globe2,
  Landmark, Leaf, MapPin, Menu, Mic, PackageCheck, Plus, RefreshCw, Route,
  ShieldCheck, Sparkles, Truck, Users, X
} from 'lucide-react'
import './styles.css'

type Lang = 'en' | 'ta'
type Role = 'producer' | 'buyer' | 'government'
type View = 'overview' | 'batches' | 'routing' | 'aggregation' | 'network' | 'impact'
type Batch = { id: string; producer: string; location: string; litres: number; mg: number; k: number; br: number; status: string; available: string }

type Copy = Record<string, string>
const en: Copy = {
  overview: 'Overview', batches: 'My batches', routing: 'Routing engine', aggregation: 'Aggregation', network: 'Industrial network', impact: 'Impact studio',
  producer: 'Producer workspace', greeting: 'Good morning, Arul.', live: 'DEMO ENVIRONMENT', subtitle: 'Turn every litre of bittern into its most valuable next step.',
  addBatch: 'Add bittern batch', routeNow: 'Route this batch', explore: 'Explore the network', voice: 'Voice help', reset: 'Reset demo',
  available: 'Available bittern', activeBatches: 'Active batches', estimatedValue: 'Estimated additional value', producers: 'Participating producers',
  utilisation: 'Utilisation rate', activity: 'Recent activity', viewAll: 'View all', profile: 'Producer profile', verified: 'Identity verified',
  location: 'Thoothukudi, Tamil Nadu', generated: 'generated', illustrative: 'Illustrative estimate', producerData: 'Producer-provided data',
  routeTitle: 'Recommended utilisation route', routeSub: 'A transparent score based on composition, quantity, distance, demand and economics.',
  recommended: 'Recommended route', magnesium: 'Magnesium recovery', bromine: 'Bromine recovery', potassium: 'Potassium recovery',
  gross: 'Gross value', transport: 'Transport', processing: 'Processing', net: 'Estimated net value', compatibility: 'Compatibility',
  factors: 'Score breakdown', composition: 'Composition fit', quantity: 'Quantity fit', distance: 'Distance', demand: 'Buyer demand', economics: 'Economics',
  findCompatible: 'Find compatible batches', aggregationTitle: 'Make fragmented supply industrially viable.', aggregationSub: 'Group nearby, compatible batches into one processor-ready consignment.', createGroup: 'Create aggregation group', totalSupply: 'Total supply', participants: 'Producers', logistics: 'Est. logistics', match: 'Best match',
  offerTitle: 'Industrial network', offerSub: 'Demand signals from fictional processors in the demo network.', makeOffer: 'Make offer', requestSample: 'Request sample', offerReceived: 'Offer received', accept: 'Accept offer',
  government: 'Government intelligence', districts: 'District activity', ledger: 'Utilisation ledger', economic: 'Economic impact', environmental: 'Environmental potential',
  govtSub: 'Traceable ecosystem intelligence for Tamil Nadu decision-makers.', registered: 'Registered producers', utilised: 'Bittern utilised', awaiting: 'Awaiting utilisation', transactions: 'Completed transactions', valueAdded: 'Value-added activity',
  scenario: 'SCENARIO MODEL', assumptions: 'Illustrative assumptions only. Not an official forecast.', potential: 'Potential environmental benefit', map: 'Tamil Nadu network', next: 'Next step',
  createRequirement: 'Create requirement', activeDemand: 'ACTIVE DEMAND SIGNAL', required: 'Required', within: 'Within', compatibleSupply: 'COMPATIBLE SUPPLY', batchMatches: 'Batch matches', ruleBased: 'RULE-BASED', processorInterest: 'Processor interest', offerSubmitted: 'Offer submitted', producerResponse: 'Producer response', selectBatch: 'Select a compatible batch to start a traceable offer.', whyMatch: 'WHY THIS MATCH', sent: 'Sent', viewImpact: 'View impact', governmentTamilNadu: 'Tamil Nadu · GOVERNMENT INTELLIGENCE', adminView: 'ADMIN VIEW · READ ONLY', liveDemoData: 'LIVE DEMO DATA', traceableMovement: 'Traceable batch movement', export: 'Export', districtsActive: 'districts active', targetRate: 'target rate', availableOn: 'Available', availability: 'Availability', roleProducer: 'SALT PRODUCER', roleBuyer: 'INDUSTRIAL BUYER', roleGovernment: 'GOVERNMENT', batchLabel: 'Batch', producerLabel: 'Producer', destinationLabel: 'Destination', statusLabel: 'Status', highActivity: 'High activity', activeLabel: 'Active', emergingLabel: 'Emerging', productiveUse: 'litres moved toward productive use',
}
const ta: Copy = {
  overview: 'மேலோட்டம்', batches: 'என் தொகுதிகள்', routing: 'வழித்தட இயந்திரம்', aggregation: 'திரட்டல்', network: 'தொழில் வலையமைப்பு', impact: 'தாக்க மையம்',
  producer: 'உற்பத்தியாளர் பணியிடம்', greeting: 'காலை வணக்கம், அருள்.', live: 'டெமோ சூழல்', subtitle: 'ஒவ்வொரு லிட்டர் பிடர்னுக்கும் மதிப்புமிக்க அடுத்த படியைத் தேர்ந்தெடுக்கவும்.',
  addBatch: 'பிடர்ன் தொகுதி சேர்க்க', routeNow: 'இந்த தொகுதியை வழிப்படுத்து', explore: 'வலையமைப்பை காண்க', voice: 'குரல் உதவி', reset: 'டெமோ மீட்டமை',
  available: 'கிடைக்கும் பிடர்ன்', activeBatches: 'செயலில் உள்ள தொகுதிகள்', estimatedValue: 'மதிப்பிடப்பட்ட கூடுதல் மதிப்பு', producers: 'பங்கேற்கும் உற்பத்தியாளர்கள்',
  utilisation: 'பயன்பாட்டு விகிதம்', activity: 'சமீபத்திய செயல்பாடு', viewAll: 'அனைத்தையும் காண்க', profile: 'உற்பத்தியாளர் சுயவிவரம்', verified: 'அடையாளம் சரிபார்க்கப்பட்டது',
  location: 'தூத்துக்குடி, தமிழ்நாடு', generated: 'உருவாக்கப்பட்டது', illustrative: 'விளக்க மதிப்பீடு', producerData: 'உற்பத்தியாளர் வழங்கிய தரவு',
  routeTitle: 'பரிந்துரைக்கப்பட்ட பயன்பாட்டு வழி', routeSub: 'கலவை, அளவு, தூரம், தேவை மற்றும் பொருளாதாரம் சார்ந்த வெளிப்படையான மதிப்பெண்.',
  recommended: 'பரிந்துரைக்கப்பட்ட வழி', magnesium: 'மெக்னீசியம் மீட்பு', bromine: 'புரோமின் மீட்பு', potassium: 'பொட்டாசியம் மீட்பு',
  gross: 'மொத்த மதிப்பு', transport: 'போக்குவரத்து', processing: 'செயலாக்கம்', net: 'மதிப்பிடப்பட்ட நிகர மதிப்பு', compatibility: 'பொருத்தம்',
  factors: 'மதிப்பெண் விவரம்', composition: 'கலவை பொருத்தம்', quantity: 'அளவு பொருத்தம்', distance: 'தூரம்', demand: 'வாங்குபவர் தேவை', economics: 'பொருளாதாரம்',
  findCompatible: 'பொருத்தமான தொகுதிகளை கண்டறிய', aggregationTitle: 'சிறு அளவு விநியோகத்தை தொழில்துறைக்கு ஏற்றதாக்குங்கள்.', aggregationSub: 'அருகிலுள்ள, பொருத்தமான தொகுதிகளை ஒரே செயலாக்க சரக்காக இணைக்கவும்.', createGroup: 'திரட்டல் குழு உருவாக்க', totalSupply: 'மொத்த விநியோகம்', participants: 'உற்பத்தியாளர்கள்', logistics: 'மதிப்பிடப்பட்ட தளவாடம்', match: 'சிறந்த பொருத்தம்',
  offerTitle: 'தொழில் வலையமைப்பு', offerSub: 'டெமோ வலையமைப்பில் உள்ள கற்பனை செயலாக்க நிறுவனங்களின் தேவை.', makeOffer: 'சலுகை அளிக்க', requestSample: 'மாதிரி கோருக', offerReceived: 'சலுகை வந்தது', accept: 'சலுகையை ஏற்க',
  government: 'அரசு நுண்ணறிவு', districts: 'மாவட்ட செயல்பாடு', ledger: 'பயன்பாட்டு பதிவு', economic: 'பொருளாதார தாக்கம்', environmental: 'சுற்றுச்சூழல் வாய்ப்பு',
  govtSub: 'தமிழ்நாடு முடிவெடுப்போருக்கான கண்காணிக்கக்கூடிய சூழல் நுண்ணறிவு.', registered: 'பதிவு செய்த உற்பத்தியாளர்கள்', utilised: 'பயன்படுத்தப்பட்ட பிடர்ன்', awaiting: 'பயன்பாட்டிற்காக காத்திருப்பவை', transactions: 'முடிந்த பரிவர்த்தனைகள்', valueAdded: 'மதிப்பு சேர்க்கப்பட்ட செயல்பாடு',
  scenario: 'சூழல் மாதிரி', assumptions: 'விளக்க அனுமானங்கள் மட்டுமே. அதிகாரப்பூர்வ கணிப்பு அல்ல.', potential: 'சாத்தியமான சுற்றுச்சூழல் நன்மை', map: 'தமிழ்நாடு வலையமைப்பு', next: 'அடுத்த படி',
  createRequirement: 'தேவையை உருவாக்கு', activeDemand: 'செயலில் உள்ள தேவை', required: 'தேவை', within: 'இதற்குள்', compatibleSupply: 'பொருத்தமான விநியோகம்', batchMatches: 'தொகுதி பொருத்தங்கள்', ruleBased: 'விதி அடிப்படையிலானது', processorInterest: 'செயலாக்குநர் ஆர்வம்', offerSubmitted: 'சலுகை சமர்ப்பிக்கப்பட்டது', producerResponse: 'உற்பத்தியாளர் பதில்', selectBatch: 'கண்காணிக்கக்கூடிய சலுகையைத் தொடங்க பொருத்தமான தொகுதியைத் தேர்ந்தெடுக்கவும்.', whyMatch: 'இந்த பொருத்தம் ஏன்', sent: 'அனுப்பப்பட்டது', viewImpact: 'தாக்கத்தை காண்க', governmentTamilNadu: 'தமிழ்நாடு · அரசு நுண்ணறிவு', adminView: 'நிர்வாக பார்வை · வாசிக்க மட்டும்', liveDemoData: 'நேரடி டெமோ தரவு', traceableMovement: 'கண்காணிக்கக்கூடிய தொகுதி நகர்வு', export: 'ஏற்றுமதி', districtsActive: 'செயலில் உள்ள மாவட்டங்கள்', targetRate: 'இலக்கு விகிதம்', availableOn: 'கிடைக்கும்', availability: 'கிடைக்கும் நிலை', roleProducer: 'உப்பு உற்பத்தியாளர்', roleBuyer: 'தொழில்துறை வாங்குபவர்', roleGovernment: 'அரசு', batchLabel: 'தொகுதி', producerLabel: 'உற்பத்தியாளர்', destinationLabel: 'இலக்கு', statusLabel: 'நிலை', highActivity: 'அதிக செயல்பாடு', activeLabel: 'செயலில்', emergingLabel: 'வளர்ந்து வரும்', productiveUse: 'லிட்டர்கள் பயனுள்ள பயன்பாட்டை நோக்கி நகர்த்தப்பட்டன',
}
const batchesSeed: Batch[] = [
  { id: 'BT-1042', producer: 'Arul Salt Works', location: 'Thoothukudi', litres: 10000, mg: 8.4, k: 3.2, br: 1.8, status: 'Listed', available: '18 Sep 2026' },
  { id: 'BT-1038', producer: 'Meenakshi Pan', location: 'Thoothukudi', litres: 5000, mg: 8.1, k: 3.4, br: 1.7, status: 'Listed', available: '19 Sep 2026' },
  { id: 'BT-1031', producer: 'Seabird Salts', location: 'Ramanathapuram', litres: 8000, mg: 8.7, k: 3.1, br: 1.9, status: 'Listed', available: '20 Sep 2026' },
  { id: 'BT-1027', producer: 'Coastal White', location: 'Nagapattinam', litres: 7000, mg: 6.2, k: 4.3, br: 1.2, status: 'Matched', available: '22 Sep 2026' },
]

function scoreRoutes(batch: Batch) {
  const base = Math.min(99, Math.round(78 + batch.mg * 1.9))
  return [
    { name: 'Magnesium recovery', score: base + 1, gross: 118000, transport: 9000, processing: 27000, color: 'navy' },
    { name: 'Bromine recovery', score: base - 5, gross: 109000, transport: 12000, processing: 34000, color: 'blue' },
    { name: 'Potassium recovery', score: base - 11, gross: 97000, transport: 8000, processing: 31000, color: 'sky' },
  ].map((route) => ({ ...route, net: route.gross - route.transport - route.processing }))
}
function money(value: number) { return `₹${(value / 1000).toFixed(0)}k` }

function App() {
  const [lang, setLang] = useState<Lang>('en')
  const [view, setView] = useState<View>('overview')
  const [role, setRole] = useState<Role>('producer')
  const [batches, setBatches] = useState(batchesSeed)
  const [demoStep, setDemoStep] = useState(4)
  const [offerAccepted, setOfferAccepted] = useState(false)
  const [showBatchForm, setShowBatchForm] = useState(false)
  const [showVoice, setShowVoice] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const t = lang === 'en' ? en : ta
  const selected = batches[0]
  const routes = useMemo(() => scoreRoutes(selected), [selected])

  useEffect(() => { document.documentElement.lang = lang === 'ta' ? 'ta' : 'en' }, [lang])
  const speak = (text: string) => {
    if ('speechSynthesis' in window) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = lang === 'ta' ? 'ta-IN' : 'en-IN'; window.speechSynthesis.speak(utterance) }
  }
  const reset = () => { setBatches(batchesSeed); setDemoStep(1); setOfferAccepted(false); setView('overview'); setRole('producer') }
  const navItems: [View, string, typeof Route][] = [['overview', t.overview, Route], ['batches', t.batches, PackageCheck], ['routing', t.routing, Sparkles], ['aggregation', t.aggregation, Users], ['network', t.network, Factory], ['impact', t.impact, Leaf]]

  return <div className="app-shell">
    <header className="topbar">
      <div className="brand" onClick={() => setView('overview')}><div className="brand-mark">A</div><div><strong>ALAM</strong><span>BITTERN INTELLIGENCE</span></div></div>
      <button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)}><Menu size={20} /></button>
      <nav className={mobileNav ? 'main-nav open' : 'main-nav'}>{navItems.map(([key, label, Icon]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => { setView(key); setMobileNav(false) }}><Icon size={16} />{label}</button>)}</nav>
      <div className="top-actions"><div className="language"><Globe2 size={15} /><button className={lang === 'en' ? 'selected' : ''} onClick={() => setLang('en')}>English</button><span>|</span><button className={lang === 'ta' ? 'selected' : ''} onClick={() => setLang('ta')}>தமிழ்</button></div><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button><button className="avatar">AS</button></div>
    </header>
    <main>
      <div className="context-bar"><span><span className="status-dot" />{t.live}</span><span className="context-separator" /> <button onClick={() => { setRole(role === 'producer' ? 'buyer' : role === 'buyer' ? 'government' : 'producer'); setView('overview') }}>VIEW AS: <b>{role === 'producer' ? t.roleProducer : role === 'buyer' ? t.roleBuyer : t.roleGovernment}</b></button><button className="voice-pill" onClick={() => { setShowVoice(true); speak(lang === 'ta' ? 'வணக்கம். ALAM குரல் உதவிக்கு வரவேற்கிறோம்.' : 'Welcome to ALAM voice help.') }}><Mic size={15} /> {t.voice}</button><button className="reset-link" onClick={reset}><RefreshCw size={14} />{t.reset}</button></div>
      {role === 'government' ? <Government t={t} lang={lang} /> : role === 'buyer' ? <Buyer t={t} onNavigate={setView} offerAccepted={offerAccepted} setOfferAccepted={setOfferAccepted} /> : <>
        {view === 'overview' && <Overview t={t} batches={batches} setView={setView} routes={routes} demoStep={demoStep} setDemoStep={setDemoStep} />}
        {view === 'batches' && <Batches t={t} batches={batches} onAdd={() => setShowBatchForm(true)} onRoute={() => setView('routing')} />}
        {view === 'routing' && <Routing t={t} batch={selected} routes={routes} lang={lang} />}
        {view === 'aggregation' && <Aggregation t={t} batches={batches} setBatches={setBatches} />}
        {view === 'network' && <Buyer t={t} onNavigate={setView} offerAccepted={offerAccepted} setOfferAccepted={setOfferAccepted} />}
        {view === 'impact' && <Impact t={t} />}
      </>}
    </main>
    {showBatchForm && <BatchModal t={t} onClose={() => setShowBatchForm(false)} onSave={(batch) => { setBatches([batch, ...batches]); setShowBatchForm(false); setView('routing') }} />}
    {showVoice && <VoicePanel t={t} lang={lang} onClose={() => setShowVoice(false)} speak={speak} />}
  </div>
}

function PageHeading({ eyebrow, title, sub, action }: { eyebrow: string; title: string; sub: string; action?: React.ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div> }
function Stat({ label, value, delta, icon: Icon, tone = 'navy' }: { label: string; value: string; delta?: string; icon: any; tone?: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong>{delta && <small>{delta}</small>}</div></div> }
function Overview({ t, batches, setView, routes, demoStep, setDemoStep }: { t: Copy; batches: Batch[]; setView: (v: View) => void; routes: any[]; demoStep: number; setDemoStep: (s: number) => void }) { return <div className="page-wrap"><PageHeading eyebrow={t.producer} title={t.greeting} sub={t.subtitle} action={<button className="primary-button" onClick={() => setView('batches')}><Plus size={17} />{t.addBatch}</button>} />
  <div className="hero-panel"><div><div className="eyebrow light">RESOURCE ROUTING ENGINE</div><h2>From by-product to <em>best-fit value.</em></h2><p>ALAM reads your batch profile, then compares utilisation pathways and industrial demand before recommending the route with the strongest estimated net value.</p><button className="light-button" onClick={() => setView('routing')}>{t.routeNow}<ArrowUpRight size={16} /></button></div><div className="route-preview"><div className="route-node"><span>BT-1042</span><b>10,000 L</b><small>PRODUCER BATCH</small></div><div className="route-line"><i /><i /><i /></div><div className="route-node highlight"><span>94%</span><b>Mg recovery</b><small>RECOMMENDED</small></div></div></div>
  <div className="stats-grid"><Stat label={t.available} value="23,000 L" delta="↑ 8.4% this month" icon={PackageCheck} /><Stat label={t.activeBatches} value="04" delta="2 ready for matching" icon={FileCheck2} tone="blue" /><Stat label={t.estimatedValue} value="₹1.18L" delta={t.illustrative} icon={Sparkles} tone="sky" /><Stat label={t.utilisation} value="68.4%" delta="Across demo network" icon={Leaf} tone="green" /></div>
  <div className="content-grid"><section className="panel activity-panel"><div className="panel-header"><div><div className="eyebrow">{t.activity}</div><h3>Supply movement</h3></div><button className="text-button" onClick={() => setView('batches')}>{t.viewAll}<ChevronRight size={15} /></button></div><div className="activity-list"><Activity icon={Check} title="Batch BT-1042 listed successfully" meta="Today, 09:42 · 10,000 L" tone="success" /><Activity icon={Users} title="Aggregation opportunity found" meta="3 compatible producers · 20,000 L" tone="blue" /><Activity icon={Bell} title="New demand signal from MagCore Industries" meta="Magnesium recovery · 15,000 L" tone="orange" /></div></section><section className="panel profile-panel"><div className="panel-header"><div><div className="eyebrow">{t.profile}</div><h3>Arul Salt Works</h3></div><ShieldCheck size={21} className="verified-icon" /></div><div className="profile-row"><div className="profile-avatar">AS</div><div><b>Arul Selvam</b><span>{t.verified}</span></div></div><div className="profile-detail"><MapPin size={15} />{t.location}</div><div className="profile-detail"><Factory size={15} />Small-scale producer · 12 years</div><div className="profile-progress"><div><span>Profile completeness</span><b>86%</b></div><div className="progress"><i style={{ width: '86%' }} /></div></div></section></div>
  <div className="demo-strip"><div><span className="demo-number">{demoStep}</span><div><b>SIH demo journey</b><span>Routing → aggregation → offer → government impact</span></div></div><div className="demo-steps">{['Batch', 'Route', 'Group', 'Offer', 'Impact'].map((step, i) => <button key={step} className={i + 1 <= demoStep ? 'done' : ''} onClick={() => { setDemoStep(i + 1); setView(i === 1 ? 'routing' : i === 2 ? 'aggregation' : i === 3 ? 'network' : i === 4 ? 'impact' : 'batches') }}><i>{i + 1 <= demoStep ? <Check size={11} /> : i + 1}</i>{step}</button>)}</div></div>
</div> }
function Activity({ icon: Icon, title, meta, tone }: { icon: any; title: string; meta: string; tone: string }) { return <div className="activity"><div className={`activity-icon ${tone}`}><Icon size={15} /></div><div><b>{title}</b><span>{meta}</span></div><ChevronRight size={15} /></div> }
function Batches({ t, batches, onAdd, onRoute }: { t: Copy; batches: Batch[]; onAdd: () => void; onRoute: () => void }) { return <div className="page-wrap"><PageHeading eyebrow="SUPPLY REGISTRY" title={t.batches} sub="Every batch stays traceable from generation to industrial utilisation." action={<button className="primary-button" onClick={onAdd}><Plus size={17} />{t.addBatch}</button>} /><div className="batch-list">{batches.map((batch, i) => <div className="batch-card" key={batch.id}><div className="batch-id"><span className={`batch-status ${i === 0 ? 'active' : ''}`} /> <b>{batch.id}</b><small>{batch.status}</small></div><div className="batch-main"><div><span>{t.totalSupply}</span><strong>{batch.litres.toLocaleString()} L</strong></div><div><span>{t.location}</span><strong>{batch.location}</strong></div><div><span>Mg · K · Br</span><strong>{batch.mg}% · {batch.k}% · {batch.br}%</strong></div><div><span>Available</span><strong>{batch.available}</strong></div></div><button className="outline-button" onClick={onRoute}>{t.routeNow}<ArrowUpRight size={15} /></button></div>)}</div></div> }
function Routing({ t, batch, routes, lang }: { t: Copy; batch: Batch; routes: any[]; lang: Lang }) { const routeLabels = [t.magnesium, t.bromine, t.potassium]; return <div className="page-wrap"><PageHeading eyebrow="ALAM DECISION SUPPORT" title={t.routeTitle} sub={t.routeSub} action={<span className="estimate-badge"><ShieldCheck size={15} />{t.illustrative}</span>} /><div className="batch-banner"><div><span className="eyebrow">ACTIVE BATCH</span><h3>{batch.id} <i>·</i> {batch.litres.toLocaleString()} L</h3><p><MapPin size={14} />{batch.location} · Available {batch.available}</p></div><div className="composition-chips"><span>Mg <b>{batch.mg}%</b></span><span>K <b>{batch.k}%</b></span><span>Br <b>{batch.br}%</b></span><small>{t.producerData}</small></div></div><div className="routes-grid">{routes.map((route, i) => <div className={`route-card ${i === 0 ? 'recommended-card' : ''}`} key={route.name}><div className="route-card-top"><div className={`route-symbol ${route.color}`}>{i === 0 ? 'Mg' : i === 1 ? 'Br' : 'K'}</div><div><span className="route-label">{i === 0 && <Sparkles size={13} />}{i === 0 ? t.recommended : 'ALTERNATIVE PATH'}</span><h3>{routeLabels[i]}</h3></div><strong className="score">{route.score}%<small>{t.compatibility}</small></strong></div><div className="route-metrics"><Metric label={t.gross} value={money(route.gross)} /><Metric label={t.transport} value={money(route.transport)} /><Metric label={t.processing} value={money(route.processing)} /><Metric label={t.net} value={money(route.net)} accent /></div><div className="route-score"><div><span>{t.compatibility}</span><b>{route.score}%</b></div><div className="progress"><i style={{ width: `${route.score}%` }} /></div></div><button className={i === 0 ? 'primary-button full' : 'outline-button full'} onClick={() => {}}>{i === 0 ? `${t.recommended} · ${lang === 'ta' ? 'தேர்ந்தெடுக்கப்பட்டது' : 'Select route'}` : 'View pathway'}<ChevronRight size={15} /></button></div>)}</div><div className="panel factors-panel"><div className="panel-header"><div><div className="eyebrow">EXPLAINABLE RULE-BASED MODEL</div><h3>{t.factors}</h3></div><span className="formula">5 weighted signals · v0.1</span></div><div className="factor-grid">{[[t.composition, 95], [t.quantity, 90], [t.distance, 88], [t.demand, 94], [t.economics, 92]].map(([label, value]) => <div className="factor" key={label as string}><div><span>{label}</span><b>{value}%</b></div><div className="progress"><i style={{ width: `${value}%` }} /></div></div>)}</div></div></div> }
function Metric({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div className={accent ? 'metric accent' : 'metric'}><span>{label}</span><b>{value}</b></div> }
function Aggregation({ t, batches, setBatches }: { t: Copy; batches: Batch[]; setBatches: (b: Batch[]) => void }) { const [created, setCreated] = useState(false); return <div className="page-wrap"><PageHeading eyebrow="SUPPLY CONSOLIDATION" title={t.aggregationTitle} sub={t.aggregationSub} action={<button className="primary-button" onClick={() => { setCreated(true); setBatches(batches.map(b => b.id === 'BT-1042' || b.id === 'BT-1038' || b.id === 'BT-1031' ? { ...b, status: 'In aggregation' } : b)) }}><Users size={17} />{t.createGroup}</button>} /><div className="aggregation-hero"><div className="aggregation-equation">{['BT-1042', 'BT-1038', 'BT-1031'].map((id, i) => <><div className="mini-batch" key={id}><span>{id}</span><b>{[10, 5, 8][i]},000 L</b><small>{batches[i]?.location}</small></div>{i < 2 && <span className="plus">+</span>}</>)}<span className="equals">=</span><div className="aggregate-result"><span>AGGREGATED BATCH</span><b>23,000 L</b><small>{created ? 'GROUP AG-2207 · READY' : 'PROCESSOR-READY TARGET'}</small></div></div></div><div className="content-grid aggregation-grid"><section className="panel"><div className="panel-header"><div><div className="eyebrow">{t.findCompatible}</div><h3>3 compatible producers</h3></div><span className="match-badge">94% MATCH</span></div>{batches.slice(0, 3).map(b => <div className="producer-line" key={b.id}><div className="mini-avatar">{b.producer.slice(0, 2).toUpperCase()}</div><div><b>{b.producer}</b><span>{b.location} · {b.litres.toLocaleString()} L</span></div><strong>{b.mg}% Mg</strong><Check size={16} className="check" /></div>)}</section><section className="panel logistics-panel"><div className="eyebrow">AGGREGATION ECONOMICS</div><h3>One truck. Three sources.</h3><div className="logistics-row"><Truck size={18} /><div><span>{t.logistics}</span><b>₹18,400</b></div></div><div className="logistics-row"><MapPin size={18} /><div><span>Average collection radius</span><b>42 km</b></div></div><div className="logistics-row"><Factory size={18} /><div><span>{t.match}</span><b>MagCore Industries</b></div></div><p className="notice"><ShieldCheck size={15} /> Grouping reduces estimated logistics cost by 31%.</p></section></div></div> }
function Buyer({ t, onNavigate, offerAccepted, setOfferAccepted }: { t: Copy; onNavigate: (v: View) => void; offerAccepted: boolean; setOfferAccepted: (v: boolean) => void }) { return <div className="page-wrap"><PageHeading eyebrow="INDUSTRIAL DEMAND NETWORK" title={t.offerTitle} sub={t.offerSub} action={<button className="primary-button" onClick={() => {}}><Plus size={17} />{t.createRequirement}</button>} /><div className="network-callout"><div className="network-icon"><Factory size={23} /></div><div><span className="eyebrow">{t.activeDemand}</span><h3>MagCore Industries · {t.magnesium}</h3><p>{t.required} 15,000 L · Mg concentration 7.5–9.5% · {t.within} 100 km of Thoothukudi</p></div><div className="network-score"><b>92%</b><span>{t.compatibility}</span></div></div><div className="content-grid"><section className="panel"><div className="panel-header"><div><div className="eyebrow">{t.compatibleSupply}</div><h3>{t.batchMatches}</h3></div><span className="match-badge">{t.ruleBased}</span></div>{['BT-1042', 'AG-2207'].map((id, i) => <div className="match-line" key={id}><div><b>{id}</b><span>{i ? '23,000 L · 3 producers · Aggregated' : '10,000 L · Arul Salt Works'}</span></div><strong>{i ? '94%' : '92%'}</strong><button className="outline-button" onClick={() => setOfferAccepted(true)}>{offerAccepted ? <><Check size={14} /> {t.sent}</> : t.makeOffer}</button></div>)}</section><section className="panel offer-panel"><div className="eyebrow">{offerAccepted ? t.offerReceived : t.processorInterest}</div><h3>{offerAccepted ? `${t.offerSubmitted} · Arul Salt Works` : t.processorInterest}</h3><div className="offer-state"><div className={offerAccepted ? 'state done' : 'state'}>{offerAccepted ? <Check size={18} /> : '01'}</div><span>{t.offerSubmitted}</span><div className="state-line" /><div className={offerAccepted ? 'state done' : 'state muted'}>{offerAccepted ? <Check size={18} /> : '02'}</div><span>{t.producerResponse}</span></div>{offerAccepted ? <button className="primary-button full" onClick={() => onNavigate('impact')}>{t.viewImpact}<ArrowUpRight size={15} /></button> : <p className="empty-message">{t.selectBatch}</p>}</section></div><div className="match-reasons"><span><Sparkles size={15} /> {t.whyMatch}</span><b>{t.composition} 95%</b><b>{t.quantity} 90%</b><b>{t.distance} 88%</b><b>{t.availability} 94%</b></div></div> }
function Government({ t, lang }: { t: Copy; lang: Lang }) { const stats = [[t.registered, '15', Users], [t.utilised, '48,200 L', PackageCheck], [t.awaiting, '22,400 L', Route], [t.transactions, '08', Check], [t.valueAdded, '₹8.4L', Sparkles]]; return <div className="page-wrap government-page"><PageHeading eyebrow={t.governmentTamilNadu} title={t.government} sub={t.govtSub} action={<span className="secure-badge"><Landmark size={15} /> {t.adminView}</span>} /><div className="stats-grid govt-stats">{stats.map(([label, value, Icon], i) => <Stat key={label as string} label={label as string} value={value as string} icon={Icon} tone={i === 4 ? 'sky' : i === 2 ? 'blue' : 'navy'} />)}</div><div className="gov-grid"><section className="panel district-panel"><div className="panel-header"><div><div className="eyebrow">{t.districts}</div><h3>{t.map}</h3></div><span className="formula">{t.liveDemoData}</span></div><div className="district-map"><div className="map-water" /><div className="tn-outline"><span className="district d1">Thoothukudi <b>42</b></span><span className="district d2">Ramanathapuram <b>21</b></span><span className="district d3">Nagapattinam <b>18</b></span><span className="district d4">Cuddalore <b>11</b></span><span className="district d5">Chengalpattu <b>08</b></span></div><div className="map-legend"><span><i className="dot large" />{t.highActivity}</span><span><i className="dot" />{t.activeLabel}</span><span><i className="dot pale" />{t.emergingLabel}</span></div></div></section><section className="panel ledger-panel"><div className="panel-header"><div><div className="eyebrow">{t.ledger}</div><h3>{t.traceableMovement}</h3></div><button className="text-button">{t.export} <ArrowUpRight size={15} /></button></div><div className="ledger-row head"><span>{t.batchLabel}</span><span>{t.producerLabel}</span><span>{t.destinationLabel}</span><span>{t.statusLabel}</span></div>{[['BT-1042', 'Arul Salt Works', 'MagCore Industries', 'MATCHED'], ['BT-1038', 'Meenakshi Pan', 'Aggregation group', 'AGGREGATED'], ['BT-1019', 'Coastal White', 'K-Potash Labs', 'PROCESSED']].map(row => <div className="ledger-row" key={row[0]}>{row.map((cell, i) => <span key={cell} className={i === 3 ? 'ledger-status' : ''}>{cell}</span>)}</div>)}</section></div><div className="impact-ribbon"><div><Leaf size={20} /><div><span>{t.potential}</span><b>48,200 {t.productiveUse}</b></div></div><div className="impact-number"><b>68.4%</b><span>{t.utilisation}</span></div><div className="impact-number"><b>6</b><span>{t.districtsActive}</span></div></div></div> }
function Impact({ t }: { t: Copy }) { const [producers, setProducers] = useState(15); const utilised = producers * 3200; return <div className="page-wrap"><PageHeading eyebrow="DECISION SUPPORT" title={t.economic} sub="Model the upside of coordinated bittern utilisation at ecosystem scale." action={<span className="scenario-badge">{t.scenario}</span>} /><div className="impact-grid"><section className="panel calculator"><div className="panel-header"><div><div className="eyebrow">INPUTS</div><h3>Scenario variables</h3></div><Sparkles size={18} /></div><label>Participating producers <b>{producers}</b><input type="range" min="5" max="60" value={producers} onChange={e => setProducers(Number(e.target.value))} /></label><label>Average bittern / producer <b>3,200 L</b><input type="range" min="1000" max="6000" defaultValue="3200" /></label><label>Utilisation target <b>72%</b><input type="range" min="20" max="100" defaultValue="72" /></label><p className="assumption"><CircleHelp size={14} />{t.assumptions}</p></section><section className="impact-output"><div className="eyebrow">PROJECTED OUTCOMES</div><h3>At {producers} participating producers</h3><div className="output-number">{utilised.toLocaleString()} <span>L</span></div><p>Estimated annual bittern moving through commercial pathways</p><div className="output-list"><div><span>Producer income</span><b>₹{(utilised * 11).toLocaleString('en-IN')}</b></div><div><span>Total transaction value</span><b>₹{(utilised * 18).toLocaleString('en-IN')}</b></div><div><span>Value-added activity</span><b>₹{(utilised * 29).toLocaleString('en-IN')}</b></div></div></section></div><div className="environment-panel"><div className="environment-icon"><Leaf size={22} /></div><div><div className="eyebrow">{t.environmental}</div><h3>Every coordinated batch creates a traceable possibility for better resource use.</h3><p>ALAM reports potential environmental benefit based on commercial utilisation, without claiming verified pollution reduction.</p></div><div className="circular-stat"><b>72%</b><span>target rate</span></div></div></div> }
function BatchModal({ t, onClose, onSave }: { t: Copy; onClose: () => void; onSave: (b: Batch) => void }) { const [litres, setLitres] = useState('12000'); return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><div className="eyebrow">NEW SUPPLY RECORD</div><h2>{t.addBatch}</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><p className="modal-help">Add producer-provided composition data. ALAM will route this batch against illustrative processor requirements.</p><div className="form-grid"><label>Quantity (L)<input value={litres} onChange={e => setLitres(e.target.value)} /></label><label>Availability date<input type="date" defaultValue="2026-09-18" /></label><label>Location<input defaultValue="Thoothukudi" /></label><label>Storage status<select defaultValue="Covered tank"><option>Covered tank</option><option>Open pond</option><option>In transit</option></select></label><label>Magnesium concentration (%)<input type="number" defaultValue="8.6" /></label><label>Potassium concentration (%)<input type="number" defaultValue="3.1" /></label><label>Bromine concentration (%)<input type="number" defaultValue="1.8" /></label><label>Production date<input type="date" defaultValue="2026-09-10" /></label></div><div className="verification-note"><FileCheck2 size={17} /><span><b>{t.producerData}</b><small>Not laboratory verified · You can update this status after testing.</small></span></div><div className="modal-actions"><button className="outline-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => onSave({ id: `BT-${1043 + Math.floor(Math.random() * 40)}`, producer: 'Arul Salt Works', location: 'Thoothukudi', litres: Number(litres) || 12000, mg: 8.6, k: 3.1, br: 1.8, status: 'Listed', available: '18 Sep 2026' })}>List batch <Check size={16} /></button></div></div></div> }
function VoicePanel({ t, lang, onClose, speak }: { t: Copy; lang: Lang; onClose: () => void; speak: (text: string) => void }) { const [listening, setListening] = useState(false); return <div className="modal-backdrop"><div className="voice-modal"><button className="icon-button close-voice" onClick={onClose}><X size={19} /></button><div className={`voice-orb ${listening ? 'listening' : ''}`}><Mic size={31} /></div><div className="eyebrow">{t.voice}</div><h2>{lang === 'ta' ? 'உங்களுக்கு எப்படி உதவலாம்?' : 'How can I help you?'}</h2><p>{lang === 'ta' ? '“என் பிடர்ன் தொகுதியை வழிப்படுத்து” என்று சொல்லிப் பாருங்கள்.' : 'Try saying “Route my bittern batch” or choose an action below.'}</p><div className="voice-actions"><button onClick={() => { setListening(true); speak(lang === 'ta' ? 'உங்கள் பிடர்ன் தொகுதியை வழிப்படுத்துகிறேன்.' : 'I am routing your bittern batch.'); setTimeout(() => setListening(false), 1800)} }><Route size={17} />{t.routeNow}</button><button onClick={() => speak(lang === 'ta' ? 'பொருத்தமான தொகுதிகளை தேடுகிறேன்.' : 'I am finding compatible batches.')}><Users size={17} />{t.findCompatible}</button></div><small>{'Speech recognition is available where supported by your browser.'}</small></div></div> }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
