import { BarChart3, Check, ChevronRight, FileCheck2, FileCheck2 as Certificate, MapPin, PackageCheck, Plus, Route, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react'
import type { Batch } from './dataTypes'
import './seller.css'

type SellerCopy = { addBatch: string; routeNow: string; location: string }

export function SellerWorkspace({ t, sellerName, batches, onAdd, onRoute }: { t: SellerCopy; sellerName: string; batches: Batch[]; onAdd: () => void; onRoute: (id: string) => void }) {
  const activeBatches = batches.filter((batch) => batch.status === 'Listed' || batch.status === 'Matched')
  const listedLitres = activeBatches.reduce((total, batch) => total + batch.litres, 0)
  const initials = sellerName.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() || 'AS'
  const isTamil = t.location.startsWith('தூ')
  return <div className="seller-page">
    <section className="seller-profile-hero"><div className="seller-identity"><div className="seller-avatar">{initials}</div><div><span className="seller-kicker">{isTamil ? 'விற்பனையாளர் சுயவிவரம்' : 'SELLER PROFILE'}</span><h1>{sellerName}</h1><p><MapPin size={14} />Thoothukudi, Tamil Nadu <span>·</span> {isTamil ? 'உப்பு உற்பத்தியாளர்' : 'Salt producer'}</p></div></div><div className="seller-verified"><ShieldCheck size={18} /><span><b>{isTamil ? 'சரிபார்க்கப்பட்டது' : 'Verified seller'}</b><small>{isTamil ? 'நம்பகமான வழங்குநர்' : 'Trusted supplier'}</small></span></div></section>
    <div className="seller-actions"><div><span className="seller-kicker">{isTamil ? 'உங்கள் விநியோக மையம்' : 'YOUR SUPPLY DESK'}</span><h2>{isTamil ? 'உங்கள் பிடர்ன் விநியோகத்தை எளிதாக நிர்வகிக்கவும்.' : 'Manage your bittern supply with ease.'}</h2><p>{isTamil ? 'ஒரு தொகுதியை பட்டியலிட்டு, பொருத்தமான தொழில்துறை பயன்பாட்டை கண்டறியுங்கள்.' : 'List a batch, see its best-fit pathway, and respond to industrial demand.'}</p></div><button className="primary-button" onClick={onAdd}><Plus size={17} />{t.addBatch}</button></div>
    <div className="seller-stat-grid"><div className="seller-stat"><span><PackageCheck size={17} />{isTamil ? 'செயலில் உள்ள விநியோகம்' : 'Active supply'}</span><strong>{listedLitres.toLocaleString()} L</strong><small>{activeBatches.length} {isTamil ? 'செயலில் உள்ள தொகுதிகள்' : 'active listings'}</small></div><div className="seller-stat"><span><TrendingUp size={17} />{isTamil ? 'மதிப்பிடப்பட்ட மதிப்பு' : 'Estimated value'}</span><strong>₹1.18L</strong><small>{isTamil ? 'விளக்க மதிப்பீடு' : 'Illustrative estimate'}</small></div><div className="seller-stat"><span><Sparkles size={17} />{isTamil ? 'சராசரி பொருத்தம்' : 'Average match'}</span><strong>94%</strong><small>{isTamil ? 'தொழில்துறை தேவை' : 'industrial demand'}</small></div></div>
    <div className="seller-insight-grid"><section className="seller-insight"><div className="seller-insight-heading"><span className="seller-kicker">{isTamil ? 'செயல்திறன்' : 'PERFORMANCE'}</span><BarChart3 size={18} /></div><h3>{isTamil ? 'உங்கள் விநியோக செயல்திறன்' : 'Supply performance'}</h3><div className="seller-bars"><i style={{ height: '48%' }} /><i style={{ height: '67%' }} /><i style={{ height: '56%' }} /><i style={{ height: '82%' }} /><i style={{ height: '74%' }} /><i style={{ height: '94%' }} /></div><div className="seller-insight-footer"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><b>+18.4% value this month</b></div></section><section className="seller-insight verification-card"><div className="seller-insight-heading"><span className="seller-kicker">{isTamil ? 'நம்பிக்கை மையம்' : 'TRUST CENTRE'}</span><ShieldCheck size={18} /></div><h3>{isTamil ? 'சரிபார்ப்பு நிலை' : 'Verification level'}</h3><div className="verification-level"><span className="verification-level-icon"><Certificate size={17} /></span><div><b>Document verified</b><small>Lab composition data is the next step</small></div><strong>2 / 3</strong></div><div className="progress"><i style={{ width: '66%' }} /></div><button className="seller-link"><Plus size={14} />Upload lab certificate</button></section></div>
    <section className="seller-listing-panel"><div className="seller-panel-heading"><div><span className="seller-kicker">{isTamil ? 'உங்கள் தொகுதிகள்' : 'YOUR LISTINGS'}</span><h2>{isTamil ? 'சந்தையில் உள்ள தொகுதிகள்' : 'Batches in the marketplace'}</h2></div><button className="seller-link" onClick={() => onRoute(activeBatches[0]?.id ?? batches[0]?.id)}>{isTamil ? 'வழித்தடத்தை காண்க' : 'View routing'}<ChevronRight size={15} /></button></div><div className="seller-listings">{activeBatches.slice(0, 3).map((batch) => <div className="seller-listing" key={batch.id}><div className="seller-listing-icon"><FileCheck2 size={18} /></div><div className="seller-listing-main"><b>{batch.id}</b><span>{batch.producer} <i>·</i> {batch.location}</span></div><div className="seller-listing-value"><strong>{batch.litres.toLocaleString()} L</strong><small>{batch.mg}% Mg · {batch.k}% K · {batch.br}% Br</small></div><span className="seller-status"><Check size={13} />{batch.status}</span><button className="seller-route" onClick={() => onRoute(batch.id)} aria-label={`${t.routeNow} ${batch.id}`}><Route size={16} /></button></div>)}</div><button className="seller-add-inline" onClick={onAdd}><Plus size={15} />{isTamil ? 'புதிய தொகுதியை பட்டியலிடுங்கள்' : 'List another batch'}</button></section>
  </div>
}
